### ISSUE TITLE
With which versions of nginx should this extension work?

### ISSUE THREAD

**Issue by dbenhur** [tszming/nginx-rewrite-request-body-module#1]
I've tried compiling it with 1.9.9, 1.8.0, and 1.6.3, and on none of these is `$request_body` populated for rewrite stage `if` directives.  I see there's been no further dev beyond the original commit.  Could authors state which version of nginx this extension worked as advertised with?

**Comment by tszming** [comment]
Last time I checked it was the nginx-1.2.3
